language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
script: ./gradlew build jacocoTestReport
after_failure:
  - cat sample-app/build/outputs/lint-results.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
